controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

import_client:
    path: /ApiRessource/ImportCSV
    controller: App\Api\Action\ImportAction
    methods: [ POST ]
