controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

import_client:
    path: /api/import-client
    controller: App\Api\Action\ImportClientAction
    methods: [ POST ]